name: Run app

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install docker.io -y

      - name: Run Docker image
        run: echo "Docker running"
